"""Content for AetherPoint service hub pages. Edit here, then run tools/gen_hubs.py."""

HUBS = [
    {
        "slug": "cybersecurity",
        "name": "Cybersecurity",
        "checkbox": "Cybersecurity",
        "icon": "shield-check",
        "title": "Cybersecurity Solutions | AetherPoint",
        "description": "Virtual CISO, penetration testing, managed firewalls, endpoint protection, SIEM, SOC as a Service, and incident response through one independent advisor.",
        "h1": "Cybersecurity Solutions for Growing Businesses",
        "intro": "From a first vulnerability assessment to a fully managed SOC, AetherPoint matches your business to the right security providers, negotiates the pricing, and stays on the account. One advisor across identify, protect, detect, and respond.",
        "sections": [
            {"h2": "Identify", "p": "Know where you stand before you spend. Assessments, testing, and compliance work that show exactly what needs attention.",
             "items": ["Virtual CISO", "Vulnerability Assessment", "Penetration Test", "Government Risk Compliance", "Security Awareness Training"]},
            {"h2": "Protect", "p": "Layered controls across the network, endpoints, email, and identity, managed by the provider and coordinated by us.",
             "items": ["Managed Firewall", "Web App Security", "Email Security", "Endpoint Protection", "Managed Cloud Firewall", "Data Loss Prevention", "Zero-Trust Framework", "Patch Management", "Identity & Access Management"]},
            {"h2": "Detect", "p": "Catch what gets through. Log management, intrusion detection, and a provider-run SOC without hiring a security team.",
             "items": ["Log Management (SIEM)", "Machine Learning Detection", "Intrusion Detection", "Intrusion Prevention", "SOC as a Service"]},
            {"h2": "Respond", "p": "A plan and a partner for the day something goes wrong.",
             "items": ["Incident Response", "Containment", "Eradication / Restore"]},
        ],
        "ai": ["Attack Identification", "Rapid Response", "Social Engineering Detection", "Biometric Authentication Systems"],
    },
    {
        "slug": "mobility",
        "name": "Mobility",
        "checkbox": "Mobility",
        "icon": "smartphone",
        "title": "Business Mobility Solutions | AetherPoint",
        "description": "Phones, tablets, eSIM, private LTE/5G, fixed wireless, and managed mobility (MDM, staging, helpdesk, plan optimization) across the major carriers.",
        "h1": "Mobility Solutions for Growing Businesses",
        "intro": "Devices, carriers, and management in one place. AetherPoint compares carrier plans and managed-mobility providers so your team gets the right devices on the right plan, with someone to call when a phone breaks.",
        "sections": [
            {"h2": "Core Products", "p": "Hardware and connectivity for the whole team, sourced at business pricing.",
             "items": ["Handsets / Phones", "Tablets", "eSIM", "MultiSIM", "Private LTE / 4G / 5G", "POTS Replacement over Cellular"]},
            {"h2": "Wireless Network", "p": "Coverage where your business actually operates, from the office to the field.",
             "items": ["LTE / 4G / 5G Connectivity", "Device Usage Management", "Application Filtering", "Detailed Reporting", "Distributed Antenna Service (DAS)", "Satellite", "Fixed Wireless"]},
            {"h2": "Managed Mobility", "p": "Let a provider handle the lifecycle: staging, management, support, and replacement.",
             "items": ["Mobile Device as a Service (MDaaS)", "Staging / Kitting", "Helpdesk", "Break / Fix", "Mobile Device Management (MDM)", "Plan Optimization", "RMA"]},
        ],
        "ai": ["Performance & Billing Optimization"],
    },
    {
        "slug": "advanced-networking",
        "name": "Advanced Networking",
        "checkbox": "Advanced Networking",
        "icon": "network",
        "title": "Advanced Networking & SD-WAN | AetherPoint",
        "description": "Dedicated fiber, broadband, 5G and satellite internet, SD-WAN with auto-failover, SASE, managed WiFi, and firewalls, quoted from hundreds of carriers.",
        "h1": "Advanced Networking Solutions for Growing Businesses",
        "intro": "Connectivity engineered for uptime. AetherPoint pulls quotes from the carriers that serve your address, designs failover so one outage never takes you down, and layers in security and monitoring from the same providers.",
        "sections": [
            {"h2": "Connectivity", "p": "Primary and backup circuits from every carrier serving your locations.",
             "items": ["Broadband / Coax", "Dedicated Fiber", "WISP / Microwave", "4G / 5G Internet", "Satellite Internet", "Aggregation"]},
            {"h2": "SD-WAN", "p": "Smart routing across circuits so traffic always takes the best path.",
             "items": ["Auto-Failover", "Intelligent Routing", "Virtual Network Functions (VNF)", "Firewall", "Application-Aware Routing"]},
            {"h2": "SASE", "p": "Network optimization and security delivered together from the cloud.",
             "items": ["Network Optimization and Security", "CASB"]},
            {"h2": "Managed WiFi", "p": "Reliable wireless for staff and guests, managed by the provider.",
             "items": ["Internal Network", "Guest Network"]},
            {"h2": "Security", "p": "Perimeter and endpoint protection that ships with the network.",
             "items": ["Firewall (Premises / Web)", "Endpoint Security", "Network Security Assessment", "Zero Trust"]},
            {"h2": "Network Management", "p": "Someone watching the network so you don't have to.",
             "items": ["Monitoring & Management"]},
        ],
        "ai": ["AI Ops", "Performance and Billing Optimization"],
    },
    {
        "slug": "cloud-managed-services",
        "name": "Cloud & Managed Services",
        "checkbox": "Cloud & Managed Services",
        "icon": "cloud",
        "title": "Cloud & Managed Services | AetherPoint",
        "description": "Public, private, and hybrid cloud, cloud connectivity, storage, colocation, DRaaS, software licensing, and helpdesk or IT outsourcing, negotiated for you.",
        "h1": "Cloud & Managed Services for Growing Businesses",
        "intro": "Move to the cloud, connect to it faster, or hand off day-to-day IT. AetherPoint compares hyperscalers, private-cloud and colocation providers, and managed-service partners so you get the right fit at negotiated pricing.",
        "sections": [
            {"h2": "Cloud Connectivity", "p": "Private, low-latency paths into the clouds you already use.",
             "items": ["Data Fabrics", "Public Cloud Connections", "AWS Direct Connect", "Azure ExpressRoute", "Oracle FastConnect", "CDN", "SaaS Platforms"]},
            {"h2": "Infrastructure", "p": "Public, private, hybrid, or bare metal, matched to your workloads and budget.",
             "items": ["Data Center & Cloud", "AWS", "Azure", "Google Cloud", "Oracle Fusion", "SAP HANA", "Private Cloud", "Hybrid & Multi-Cloud", "IaaS", "PaaS", "Bare Metal", "DRaaS", "Backup as a Service (BUaaS)", "Data Center Colocation"]},
            {"h2": "Storage", "p": "Cloud-based storage sized and tiered for how you use it.",
             "items": ["Cloud-Based Storage", "Object Storage", "File Storage", "Block Storage"]},
            {"h2": "License & Application", "p": "Stop overpaying for software you're not using.",
             "items": ["Software License Management", "ERP Management", "Software License Optimization", "Software Licensing"]},
            {"h2": "Managed & Professional Services", "p": "Outsource the helpdesk, the migration, or the whole IT function.",
             "items": ["Helpdesk as a Service", "IT Outsourcing (ITO)", "Cloud Migration", "Application Management (ERP, CRM, etc.)"]},
        ],
        "ai": ["Application Optimization", "Robotic Process Automation", "Data Lakehouse", "Load Balancing", "Predictive Analytics", "LLM as a Service"],
    },
    {
        "slug": "iot",
        "name": "IoT",
        "checkbox": "IoT",
        "icon": "cpu",
        "title": "IoT Solutions | AetherPoint",
        "description": "Connected sensors, cameras and access control, energy monitoring, EV charging, and telematics for agriculture, manufacturing, logistics, and hospitality.",
        "h1": "IoT Solutions for Growing Businesses",
        "intro": "Connect the physical side of your business. AetherPoint sources sensors, cameras, energy monitoring, and the connectivity behind them, then pairs it with reporting you can act on.",
        "sections": [
            {"h2": "Sensors", "p": "Measure what matters, wherever it is.",
             "items": ["Temperature", "Pressure", "Soil Moisture / Content"]},
            {"h2": "Physical Security", "p": "See and control who comes and goes.",
             "items": ["Cameras", "Access Control", "Video Analytics"]},
            {"h2": "Energy", "p": "Monitor and manage consumption across sites.",
             "items": ["Electric", "Gas", "Solar", "EV Chargers"]},
            {"h2": "Vertical-Specific", "p": "Packaged solutions for the industries that run on IoT.",
             "items": ["Smart City", "Agriculture", "Manufacturing", "Logistics", "Hospitality"]},
            {"h2": "Reporting", "p": "Turn device data into decisions.",
             "items": ["Geo-Fence", "Detailed Use", "Velocity / Acceleration"]},
        ],
        "ai": ["Computer Vision", "Telematics", "IoT Data Analysis"],
    },
]
